const movies = [
    { title: "Avatar 1", year: 2009, genre: "Action, Fantasy", watched: true },
    { title: "Avatar 2: The Way of Water", year: 2022, genre: "Action, Fantasy", watched: true },
    { title: "Avatar 3: Fire and Ash", year: 2025, genre: "Action, Fantasy", watched: false },
    { title: "Avatar 4", year: 2029, genre: "Action, Fantasy", watched: false },
    { title: "Avatar 5", year: 2031, genre: "Action, Fantasy", watched: false },
    { title: "Back to the future Part 1", year: 1985, genre: "Comedy, Sci-Fi", watched: false },
    { title: "Back to the future Part 2", year: 1989, genre: "Action, Sci-Fi", watched: false },
    { title: "Back to the future Part 3", year: 1990, genre: "Action, Sci-Fi", watched: false },
    { title: "Bad Boys I", year: 1995, genre: "Action, Comedy", watched: false },
    { title: "Bad Boys II", year: 2003, genre: "Action, Comedy", watched: false },
    { title: "Bad Boys for Life (3)", year: 2020, genre: "Action, Comedy", watched: false },
    { title: "Bad Boys: Ride or Die (4)", year: 2024, genre: "Action, Comedy", watched: false },
    { title: "Batman 1: Begins", year: 2005, genre: "Action, Crime", watched: true },
    { title: "Batman 2: The Dark Knight", year: 2008, genre: "Action, Crime", watched: true },
    { title: "Batman 3: The Dark Knight Rises", year: 2012, genre: "Action, Crime", watched: true },
    { title: "Enola Holmes 1", year: 2020, genre: "Mystery, Adventure", watched: false },
    { title: "Enola Holmes 2", year: 2022, genre: "Mystery, Adventure", watched: false },
    { title: "Extraction 1", year: 2020, genre: "Action, Thriller", watched: true },
    { title: "Extraction 2", year: 2023, genre: "Action, Thriller", watched: true },
    { title: "Fast and Furious 1", year: 2001, genre: "Action, Crime", watched: true },
    { title: "Fast and Furious 2: 2 Fast 2 Furious", year: 2003, genre: "Action, Crime", watched: false },
    { title: "Fast and Furious 3: Tokyo Drift", year: 2006, genre: "Action, Crime", watched: false },
    { title: "Fast and Furious 4", year: 2009, genre: "Action, Crime", watched: false },
    { title: "Fast and Furious 5: Fast Five", year: 2011, genre: "Action, Crime", watched: false },
    { title: "Fast and Furious 6", year: 2013, genre: "Action, Crime", watched: false },
    { title: "Fast and Furious 7", year: 2015, genre: "Action, Crime", watched: false },
    { title: "Fast and Furious 8: The Fate of the Furious", year: 2017, genre: "Action, Crime", watched: false },
    { title: "Fast and Furious: Hobbs & Shaw", year: 2019, genre: "Action, Crime", watched: false },
    { title: "Fast and Furious 9: F9", year: 2021, genre: "Action, Crime", watched: false },
    { title: "Fast and Furious 10: Fast X", year: 2023, genre: "Action, Crime", watched: false },
    { title: "Gladiator", year: 2000, genre: "Action, Drama", watched: false },
    { title: "Gladiator II", year: 2024, genre: "Action, Drama", watched: false },
    { title: "Grown ups", year: 2010, genre: "Comedy", watched: false },
    { title: "Grown ups 2", year: 2013, genre: "Comedy", watched: false },
    { title: "Harry Potter 1: And the Sorcerer's Stone", year: 2001, genre: "Fantasy, Adventure", watched: true },
    { title: "Harry Potter 2: And the Chamber of Secrets", year: 2002, genre: "Fantasy, Adventure", watched: true },
    { title: "Harry Potter 3: And the Prisoner of Azkaban", year: 2004, genre: "Fantasy, Adventure", watched: true },
    { title: "Harry Potter 4: And the Goblet of Fire", year: 2005, genre: "Fantasy, Adventure", watched: true },
    { title: "Harry Potter 5: And the Order of the Phoenix", year: 2007, genre: "Fantasy, Adventure", watched: true },
    { title: "Harry Potter 6: And the Half-Blood Prince", year: 2009, genre: "Fantasy, Adventure", watched: true },
    { title: "Harry Potter 7: And the Deathly Hallows Part 1", year: 2010, genre: "Fantasy, Adventure", watched: true },
    { title: "Harry Potter 8: And the Deathly Hallows Part 2", year: 2011, genre: "Fantasy, Adventure", watched: true },
    { title: "Jack Reacher", year: 2012, genre: "Action, Mystery", watched: true },
    { title: "Jack reacher : Never go back", year: 2016, genre: "Action, Mystery", watched: true },
    { title: "Dr. No (007)", year: 1962, genre: "Action, Adventure", watched: false },
    { title: "From Russia with Love (007)", year: 1963, genre: "Action, Adventure", watched: false },
    { title: "Goldfinger (007)", year: 1964, genre: "Action, Adventure", watched: false },
    { title: "Thunderball (007)", year: 1965, genre: "Action, Adventure", watched: false },
    { title: "You Only Live Twice (007)", year: 1967, genre: "Action, Adventure", watched: false },
    { title: "On Her Majesty's Secret Service (007)", year: 1969, genre: "Action, Adventure", watched: false },
    { title: "Diamonds Are Forever (007)", year: 1971, genre: "Action, Adventure", watched: false },
    { title: "Live and Let Die (007)", year: 1973, genre: "Action, Adventure", watched: false },
    { title: "The Man with the Golden Gun (007)", year: 1974, genre: "Action, Adventure", watched: false },
    { title: "The Spy Who Loved Me (007)", year: 1977, genre: "Action, Adventure", watched: false },
    { title: "Moonraker (007)", year: 1979, genre: "Action, Adventure", watched: false },
    { title: "For Your Eyes Only (007)", year: 1981, genre: "Action, Adventure", watched: false },
    { title: "Octopussy (007)", year: 1983, genre: "Action, Adventure", watched: false },
    { title: "A View to a Kill (007)", year: 1985, genre: "Action, Adventure", watched: false },
    { title: "The Living Daylights (007)", year: 1987, genre: "Action, Adventure", watched: false },
    { title: "Licence to Kill (007)", year: 1989, genre: "Action, Adventure", watched: false },
    { title: "GoldenEye (007)", year: 1995, genre: "Action, Adventure", watched: false },
    { title: "Tomorrow Never Dies (007)", year: 1997, genre: "Action, Adventure", watched: false },
    { title: "The World Is Not Enough (007)", year: 1999, genre: "Action, Adventure", watched: false },
    { title: "Die Another Day (007)", year: 2002, genre: "Action, Adventure", watched: false },
    { title: "Casino Royale (1967) (007)", year: 1967, genre: "Comedy, Adventure", watched: false },
    { title: "Never Say Never Again (007)", year: 1983, genre: "Action, Adventure", watched: false },
    { title: "Casino Royale (2006) (007)", year: 2006, genre: "Action, Adventure", watched: true },
    { title: "Quantum of Solace (007)", year: 2008, genre: "Action, Adventure", watched: true },
    { title: "Skyfall (007)", year: 2012, genre: "Action, Adventure", watched: true },
    { title: "Spectre (007)", year: 2015, genre: "Action, Adventure", watched: true },
    { title: "No Time to Die (007)", year: 2021, genre: "Action, Adventure", watched: true },
    { title: "John Wick: Chapter 1", year: 2014, genre: "Action, Thriller", watched: true },
    { title: "John Wick: Chapter 2", year: 2017, genre: "Action, Thriller", watched: true },
    { title: "John Wick: Chapter 3 - Parabellum", year: 2019, genre: "Action, Thriller", watched: true },
    { title: "John Wick: Chapter 4", year: 2023, genre: "Action, Thriller", watched: true },
    { title: "John Wick: Ballerina", year: 2025, genre: "Action, Thriller", watched: true },
    { title: "Joker", year: 2019, genre: "Crime, Drama", watched: false },
    { title: "Joker Folie à Deux", year: 2024, genre: "Crime, Drama", watched: false },
    { title: "Maleficent", year: 2014, genre: "Family, Drama", watched: true },
    { title: "Maleficent: Mistress of Evil", year: 2019, genre: "Family, Adventure", watched: true },
    { title: "Mean Girls (2004)", year: 2004, genre: "Comedy", watched: true },
    { title: "Mean Girls (2024)", year: 2024, genre: "Comedy, Musical", watched: false },
    { title: "Men in Black 1", year: 1997, genre: "Action, Sci-Fi", watched: true },
    { title: "Men in Black 2", year: 2002, genre: "Action, Sci-Fi", watched: true },
    { title: "Men in Black 3", year: 2012, genre: "Action, Sci-Fi", watched: true },
    { title: "Men in Black 4: International", year: 2019, genre: "Action, Sci-Fi", watched: true },
    { title: "Mission Impossible I", year: 1996, genre: "Action, Adventure", watched: true },
    { title: "Mission Impossible II", year: 2000, genre: "Action, Adventure", watched: true },
    { title: "Mission Impossible III", year: 2006, genre: "Action, Adventure", watched: true },
    { title: "Mission Impossible IV: Ghost Protocol", year: 2011, genre: "Action, Adventure", watched: true },
    { title: "Mission Impossible V: Rogue Nation", year: 2015, genre: "Action, Adventure", watched: true },
    { title: "Mission Impossible VI: Fallout", year: 2018, genre: "Action, Adventure", watched: true },
    { title: "Mission Impossible VII: Dead Reckoning Part 1", year: 2023, genre: "Action, Adventure", watched: true },
    { title: "Mission Impossible VIII: The Final Reckoning", year: 2024, genre: "Action, Adventure", watched: true },
    { title: "My Fault", year: 2023, genre: "Thriller, Mystery", watched: false },
    { title: "Your fault", year: 2024, genre: "Thriller, Mystery", watched: false },
    { title: "Our fault", year: 2025, genre: "Thriller, Mystery", watched: false },
    { title: "Now You See Me 1", year: 2013, genre: "Thriller, Mystery", watched: true },
    { title: "Now You See Me 2", year: 2016, genre: "Thriller, Mystery", watched: true },
    { title: "Now You See Me 3", year: 2025, genre: "Thriller, Mystery", watched: true },
    { title: "Pirates of the Caribbean: The Curse of the Black Pearl", year: 2003, genre: "Adventure, Fantasy", watched: false },
    { title: "Pirates of the Caribbean: Dead Man's Chest", year: 2006, genre: "Adventure, Fantasy", watched: false },
    { title: "Pirates of the Caribbean: At World's End", year: 2007, genre: "Adventure, Fantasy", watched: false },
    { title: "Pirates of the Caribbean: On Stranger Tides", year: 2011, genre: "Adventure, Fantasy", watched: false },
    { title: "Pirates of the Caribbean: Dead Men Tell No Tales", year: 2017, genre: "Adventure, Fantasy", watched: false },
    { title: "Rush Hour 1", year: 1998, genre: "Action, Comedy", watched: false },
    { title: "Rush Hour 2", year: 2001, genre: "Action, Comedy", watched: false },
    { title: "Rush Hour 3", year: 2007, genre: "Action, Comedy", watched: false },
    { title: "Sherlock Holmes 1", year: 2009, genre: "Action, Mystery", watched: true },
    { title: "Sherlock Holmes 2: A Game of Shadows", year: 2011, genre: "Action, Mystery", watched: true },
    { title: "Star Wars Chapter IV: A New Hope", year: 1977, genre: "Sci-Fi, Adventure", watched: false },
    { title: "Star Wars Chapter V: The Empire Strikes Back", year: 1980, genre: "Sci-Fi, Adventure", watched: false },
    { title: "Star Wars Chapter VI: Return of the Jedi", year: 1983, genre: "Sci-Fi, Adventure", watched: false },
    { title: "Star Wars Chapter I: The Phantom Menace", year: 1999, genre: "Sci-Fi, Adventure", watched: false },
    { title: "Star Wars Chapter II: Attack of the Clones", year: 2002, genre: "Sci-Fi, Adventure", watched: false },
    { title: "Star Wars Chapter III: Revenge of the Sith", year: 2005, genre: "Sci-Fi, Adventure", watched: false },
    { title: "Star Wars Chapter VII: The Force Awakens", year: 2015, genre: "Sci-Fi, Adventure", watched: false },
    { title: "Star Wars Chapter VIII: The Last Jedi", year: 2017, genre: "Sci-Fi, Adventure", watched: false },
    { title: "Star Wars Chapter IX: The Rise of Skywalker", year: 2019, genre: "Sci-Fi, Adventure", watched: false },
    { title: "Taken 1", year: 2008, genre: "Action, Thriller", watched: false },
    { title: "Taken 2", year: 2012, genre: "Action, Thriller", watched: false },
    { title: "Taken 3", year: 2014, genre: "Action, Thriller", watched: false },
    { title: "Ted", year: 2012, genre: "Comedy , Animation", watched: true },
    { title: "Ted 2", year: 2015, genre: "Comedy , Animation", watched: true },
    { title: "Terminator 1", year: 1984, genre: "Action, Sci-Fi", watched: true },
    { title: "Terminator 2: Judgement Day", year: 1991, genre: "Action, Sci-Fi", watched: true },
    { title: "Terminator 3: Rise of the Machines", year: 2003, genre: "Action, Sci-Fi", watched: true },
    { title: "Terminator 4: Salvation", year: 2009, genre: "Action, Sci-Fi", watched: true },
    { title: "Terminator 5: Genisys", year: 2015, genre: "Action, Sci-Fi", watched: true },
    { title: "Terminator 6: Dark Fate", year: 2019, genre: "Action, Sci-Fi", watched: true },
    { title: "The Accountant", year: 2016, genre: "Action, Thriller", watched: false },
    { title: "The Accountant 2", year: 2025, genre: "Action, Thriller", watched: false },
    { title: "The Batman", year: 2022, genre: "Action, Crime", watched: true },
    { title: "The Batman 2", year: 2026, genre: "Action, Crime", watched: false },
    { title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe", year: 2005, genre: "Fantasy, Adventure", watched: true },
    { title: "The Chronicles of Narnia: Prince Caspian", year: 2008, genre: "Family, Adventure", watched: true },
    { title: "The Chronicles of Narnia: The Voyage of the Dawn Treader", year: 2010, genre: "Family, Adventure", watched: true },
    { title: "The Expendables 1", year: 2010, genre: "Action, Thriller", watched: false },
    { title: "The Expendables 2", year: 2012, genre: "Action, Thriller", watched: false },
    { title: "The Expendables 3", year: 2014, genre: "Action, Thriller", watched: false },
    { title: "The Expendables 4", year: 2023, genre: "Action, Thriller", watched: false },
    { title: "The Family Plan", year: 2023, genre: "Action, Comedy", watched: true },
    { title: "The Family Plan 2", year: 2025, genre: "Action, Comedy", watched: true },
    { title: "The Godfather Part 1", year: 1972, genre: "Crime, Drama", watched: true },
    { title: "The Godfather Part 2", year: 1974, genre: "Crime, Drama", watched: true },
    { title: "The Godfather Part 3", year: 1990, genre: "Crime, Drama", watched: true },
    { title: "The Hangover", year: 2009, genre: "Comedy", watched: false },
    { title: "The Hangover Part II", year: 2011, genre: "Comedy", watched: false },
    { title: "The Hangover Part III", year: 2013, genre: "Comedy", watched: false },
    { title: "The Hobbit 1: An Unexpected Journey", year: 2012, genre: "Adventure, Fantasy", watched: false },
    { title: "The Hobbit 2: The Desolation of Smaug ", year: 2013, genre: "Adventure, Fantasy", watched: false },
    { title: "The Hobbit 3: The Battle of the Five Armies", year: 2014, genre: "Adventure, Fantasy", watched: false },
    { title: "The Karate Kid I", year: 1972, genre: "Crime, Drama", watched: true },
    { title: "The Karate Kid II", year: 1974, genre: "Crime, Drama", watched: false },
    { title: "The Karate Kid III", year: 1990, genre: "Crime, Drama", watched: false },
    { title: "The Karate Kid 2010", year: 2010, genre: "Crime, Drama", watched: true },
    { title: "The Karate Kid Legends", year: 2025, genre: "Action, Drama", watched: false },
    { title: "The Kingsmen: The Secret Service", year: 2014, genre: "Action, Comedy", watched: false },
    { title: "TheKingsmen: The Golden Circle", year: 2017, genre: "Action, War", watched: false },
    { title: "The King's Man", year: 2021, genre: "Action, War", watched: false },
    { title: "The Lord of the Rings: The Fellowship of the Ring", year: 2001, genre: "Adventure, Fantasy", watched: false },
    { title: "The Lord of the Rings: The Two Towers", year: 2002, genre: "Adventure, Fantasy", watched: false },
    { title: "The Lord of the Rings: The Return of the King", year: 2003, genre: "Adventure, Fantasy", watched: false },
    { title: "The Matrix 1", year: 1999, genre: "Action, Sci-Fi", watched: true },
    { title: "The Matrix 2: Reloaded", year: 2003, genre: "Action, Sci-Fi", watched: true },
    { title: "The Matrix 3: Revolutions", year: 2003, genre: "Action, Sci-Fi", watched: true },
    { title: "The Matrix 4: Resurrections", year: 2021, genre: "Action, Sci-Fi", watched: true },
    { title: "The Princess Switch", year: 2018, genre: "Comedy, Romance", watched: true },
    { title: "The Princess Switch 2: Switched Again", year: 2020, genre: "Comedy, Romance", watched: false },
    { title: "The Princess Switch 3: Romancing the Star", year: 2021, genre: "Comedy, Romance", watched: false },
    { title: "Top Gun: Maverick", year: 2022, genre: "Action, Drama", watched: true },
    { title: "Top Gun", year: 1986, genre: "Action, Drama", watched: true },
    { title: "Transformers 1", year: 2007, genre: "Action, Sci-Fi", watched: true },
    { title: "Transformers 2: Revenge of the Fallen", year: 2009, genre: "Action, Sci-Fi", watched: true },
    { title: "Transformers 3: Dark of the Moon", year: 2011, genre: "Action, Sci-Fi", watched: true },
    { title: "Transformers 4: Age of Extinction", year: 2014, genre: "Action, Sci-Fi", watched: true },
    { title: "Transformers 5: The Last Knight", year: 2017, genre: "Action, Sci-Fi", watched: true },
    { title: "Transformers 6: Bumblebee", year: 2018, genre: "Action, Sci-Fi", watched: true },
    { title: "Transformers 7: Rise of the Beasts", year: 2023, genre: "Action, Sci-Fi", watched: true },
    { title: "Transformers One (Animated Film)", year: 2024, genre: "Action, Sci-Fi", watched: false },
    { title: "XXX (2002)", year: 2002, genre: "Action, Thriller", watched: false },
    { title: "XXX 2: State of the Union", year: 2005, genre: "Action, Thriller", watched: false },
    { title: "XXX: Return of Xander Cage", year: 2017, genre: "Action, Thriller", watched: true },
    { title: "American Pie 1", year: 1999, genre: "Comedy, Romance", watched: true },
    { title: "American Pie 2", year: 2001, genre: "Comedy, Romance", watched: true },
    { title: "American Wedding (3)", year: 2003, genre: "Comedy, Romance", watched: true },
    { title: "American Pie: Reunion (4)", year: 2012, genre: "Comedy, Romance", watched: true },
    { title: "American Pie Presents: Band Camp", year: 2005, genre: "Comedy", watched: false },
    { title: "American Pie Presents: The Naked Mile", year: 2006, genre: "Comedy", watched: false },
    { title: "American Pie Presents: Beta House", year: 2007, genre: "Comedy", watched: false },
    { title: "American Pie Presents: The Book of Love", year: 2009, genre: "Comedy", watched: false },
    { title: "American Pie Presents: Girls Rules", year: 2020, genre: "Comedy", watched: false }
];

const movieTableBody = document.getElementById('movieTableBody');

function createMovieRow(movie, index) {
    const row = document.createElement('tr');
    row.innerHTML = `
        <td>${index + 1}</td>
        <td>${movie.title}</td>
        <td>${movie.year}</td>
        <td>${movie.genre}</td>
        <td><span class="${movie.watched ? 'watched' : 'unwatched'}">${movie.watched ? '✓ Watched' : '✗ Unwatched'}</span></td>
    `;
    return row;
}

movies.forEach((movie, i) => {
    movieTableBody.appendChild(createMovieRow(movie, i));
});
