const movies = [  { title: "50 First Dates", year: 2014, genre: "Romantic , Comedy", watched: true },
        { title: "(500) Days of Summer", year: 2009, genre: "Comedy, Romance", watched: true },
        { title: "1917", year: 2019, genre: "Drama, War", watched: false },{ title: "A Dog's Purpose", year: 2017, genre: "Adventure, Comedy", watched: false },
        { title: "A house of Dynamite  ", year:2025 , genre: " Thriller , Drama  ",  watched: false},
        { title: "Air", year: 2023, genre: "Biography, Drama", watched:true },
        { title: "Anyone But You", year: 2024, genre: "Romance, Comedy", watched:true },
        { title: "All Quiet on the Western Front", year: 2022, genre: "Drama, War", watched:true },
        { title: "All the Bright Places", year: 2020, genre: "Drama, Romance", watched:true },
        { title: "Baby Driver", year: 2017, genre: "Action, Crime", watched:true },
        { title: "Barefoot", year: 2014, genre: "Romantic , Comedy", watched: true },
        { title: "Before Dawn", year: 1995, genre: "Drama, Romance", watched: false },
        { title: "blade runner 2049  ", year:2017 , genre: " sci-fi,Action   ",  watched: false },
        { title: "Blended", year: 2014, genre: "Romantic , Comedy", watched: true },
        { title: "Bridge to Terabithia", year: 2007, genre: "Adventure, Drama", watched: false },
        { title: "Coda", year: 2021, genre: "Musical , Comedy", watched: false },
        { title: "Demolition", year: 2015, genre: "Drama", watched: false },
        { title: "Dumb and Dumber", year: 1994, genre: "Comedy", watched: false },
        { title: "Dunkirk", year: 2017, genre: "Action, Drama", watched: true },
        { title: "Enough", year: 2002, genre: "Thriller , Action", watched: false },
        { title: "Eternal Sunshine of the Spotless Mind", year: 2004, genre: "Drama, Romance", watched: false },
        { title: "Euro Trip", year: 2004, genre: "Comedy, Adventure", watched: true },
        { title: "F1", year: 2025, genre: "Documentary", watched: true },
        { title: "Fight Club", year: 1999, genre: "Drama", watched: true },
        { title: "Five Feet Apart", year: 2019, genre: "Drama, Romance", watched: false },
        { title: "Fly me to the moon", year: 2024, genre: "Action , rom-com", watched: false },
        { title: "Ford v Ferrari", year: 2019, genre: "Biography, Drama", watched: true },
        { title: "Forrest Gump", year: 1994, genre: "Drama, Romance", watched: true },
        { title: "Free Guy", year: 2021, genre: "Action, Comedy", watched: true },
        { title: "Friends with Benefits", year: 2011, genre: "Comedy, Romance", watched:true },
        { title: "Ghosted", year: 2023, genre: "Romance, Action", watched:true },
        { title: "Gifted", year: 2017, genre: "Drama", watched: false },
        { title: "Good Luck Chuck", year: 2007 , genre: "Comedy , Romance   ",  watched: true   },
        { title: "Gran Turismo", year: 2023, genre: "Action, Drama", watched:true },
        { title: "Hachiko: A Dog's Tale", year: 2009, genre: "Drama, Family", watched: false },
        { title: "Hitman", year: 2023, genre: "Action, Thriller", watched:true },
        { title: "Holidate", year: 2020, genre: "Romance, Comedy", watched: false }, 
        { title: "How to lose a guy in 10 days", year: 2003, genre: "Romantic , Comedy", watched: true },
        { title: "I am Sam", year: 2001, genre: "Drama", watched: false },
        { title: "Inception", year: 2010, genre: "Action, Sci-Fi", watched:true },
        { title: "Inglorious Basterds", year: 2009, genre: "Adventure, War", watched: true },
        { title: "Instant Family", year: 2018, genre: "Comedy, Drama", watched: true },
        { title: "Interstellar", year: 2014, genre: "Sci-Fi, Drama", watched:true },
        { title: "Jerry Maguire", year: 1996, genre: "Drama, romance , comedy", watched: true },
        { title: "Jersey Girl", year: 2004, genre: "Romantic , Comedy", watched: true }, 
        { title: "Jobs", year: 2013, genre: "Biography, Drama", watched: true },
        { title: "Jumanji", year: 1995, genre: "Adventure, Family", watched:true },
        { title: "Just Go With It", year: 2011, genre: "Comedy, Romance", watched: false },
        { title: "Just Married", year: 2003, genre: "Comedy, Romance", watched: true},
        { title: "kiss kiss bang bang", year: 2005, genre: " Action , Comedy   ", watched: false },
        { title: "La La Land", year: 2016, genre: "Drama, Romance", watched: true },
        { title: "Love and other Drugs", year: 2010, genre: "Comedy , Romance", watched: false },
        { title: "Me Before You", year: 2016, genre: "Drama, Romance", watched:true  },
        { title: "Meet Joe Black", year: 1998, genre: "Drama, Romance", watched:true },
        { title: "Mr and Mrs Smith", year: 2005, genre: "Action , Comedy", watched: false },
        { title: "Napoleon", year: 2023, genre: "Biography, Drama", watched:true  },
        { title: "No Hard Feelings", year: 2023, genre: "Comedy, Drama", watched:true },
        { title: "No Strings Attached", year: 2011, genre: "Comedy, Romance", watched:true },
        { title: "Nutcracker", year: 2024, genre: "Fantasy, Family", watched: false },
        { title: "New York, I Love You", year: 2008, genre: "Romance, Drama", watched:true },
        { title: "Oppenheimer", year: 2023, genre: "Biography, Drama", watched:true },
        { title: "Pawn Sacrifice", year: 2014, genre: "Biography, Drama", watched: true },
        { title: "queen of chess ", year:2026 , genre: " Biography , sports   ",  watched: false },
        { title: "Red One", year: 2024, genre: "Action , Comedy", watched: false },
        { title: "Rush", year:2013, genre: " Sport , Action  ",  watched: false   },
        { title: "Serendipity", year: 2001, genre: "Romance, Comedy", watched:true },
        { title: "she's the man ", year:2000 , genre: " comedy ,sport",  watched: true },
        { title: "Siberia", year: 2018, genre: "Crime, Romance", watched: false },
        { title: "Sick Girl", year: 2023, genre: "Comedy, Horror", watched:true },
        { title: "Snowden", year: 2016, genre: "Biography, Drama", watched: true},
        { title: "Steve Jobs", year: 2015, genre: "Biography, Drama", watched:true  },
        { title: "Superbad", year: 2007, genre: "Comedy", watched: true },
        { title: "tenet  ", year:2020 , genre: " Action , sci-fi   ",  watched: false },
        { title: "The 40-Year-Old Virgin", year: 2005, genre: "Comedy, Romance", watched:true  },
        { title: "The Amateur", year: 2025, genre: "Action, Thriller", watched: false },
        { title: "The Blind Side", year: 2009, genre: "Sport , Drama", watched: false  },
        { title: "The Departed", year: 2006, genre: "Crime, Drama", watched: false },
        { title: "The Dictator", year: 2012, genre: "Comedy", watched: false },
        { title: "The Fall Guy", year: 2024, genre: "Action, Thriller", watched: true },
        { title: "The Fault in Our Stars", year: 2014, genre: "Drama, Romance", watched:true  },
        { title: "The Girl Next Door", year: 2004, genre: "Comedy, Romance", watched:true },
        { title: "the gorge  ", year:2025 , genre: " Action , sci-fi   ",  watched: false },
        { title: "the gray man", year: 2022, genre: "Action , mystery , thriller", watched: false },
        { title: "The Imitation Game", year: 2014, genre: "Biography, Drama", watched: true },
        { title: "The Intern", year: 2015, genre: "Comedy, Drama", watched: true},
        { title: "The Martian", year: 2015, genre: "Sci-Fi, Drama", watched: true },
        { title: "The Ministry of Ungentlemanly Warfare", year: 2024, genre: "Action,Comedy,War", watched: false } ,
        { title: "The Other Zoey", year: 2024, genre: "Romance, Comedy", watched:true  },
        { title: "The parent trap", year: 1998, genre: "Drama, rom-com", watched: true },
        { title: "The proposal ", year:2009 , genre: " Comedy , Romance",  watched: true },
        { title: "The Rebound", year: 2009, genre: "Comedy, Romance", watched: true },
        { title: "The Running Man", year: 2025, genre: "Sci-fi Adventure", watched: false },
        { title: "The Shawshank Redemption", year: 1994, genre: "Drama", watched: true},
        { title: "The Social Network", year: 2010, genre: "Biography, Drama", watched:true },
        { title: "The Town", year: 2010, genre: "Crime, Drama", watched: true },
        { title: "The Wolf of Wall Street", year: 2013, genre: "Biography, Comedy", watched: true  },
        { title: "The Words", year: 2012, genre: "Action , drama , romance", watched: false },
        { title: "Uptown Girls ", year: 2003, genre: "comedy , romance", watched: true },
        { title: "Vacation", year: 2015, genre: "Comedy , Adventure", watched: false  },
        { title: "War Machine  ", year:2026 , genre: " Action , Sci-fi   ",  watched: false },
        { title: "Wedding Daze", year: 2006, genre: "Comedy, Romance", watched: true },
        { title: "We Live in Time", year: 2024, genre: "Drama, Romance", watched:true},
        { title: "We're the Millers", year: 2013, genre: "Comedy, Crime", watched: true },
        { title: "Why Him?", year: 2016, genre: "Comedy, Romance", watched: true }
      //  { title: "Empty  ", year:2000 , genre: " Gamma , delta   ",  watched: true }
];


const movieTableBody = document.getElementById('movieTableBody');

function createMovieRow(movie) {
    const row = document.createElement('tr');
    row.innerHTML = `
        <td>${movie.title}</td>
        <td>${movie.year}</td>
        <td>${movie.genre}</td>
        <td class="${movie.watched ? 'watched' : 'unwatched'}">${movie.watched ? 'Watched' : 'Unwatched'}</td>
    `;
    return row;
}

movies.forEach(movie => {
    movieTableBody.appendChild(createMovieRow(movie));
});